#!/usr/bin/env bash
# -*- mode: shell-script; -*-
# genbb
# Author: F. Mauger <mauger@lpccaen.in2p3.fr>

appname="genbb"

debug=0
config_file=
seed=
nevents=
output_file=
interactive=0
tmp_dir=
tmp_conf=

function my_exit ()
{
    if [ -f ${tmp_conf} ]; then
	rm -f ${tmp_conf} 
    fi
    exit $1
}

function usage ()
{
    cat<<EOF

genbb - generate primary particles using the 'genbb_help' library

Usage:

 Batch mode:

  genbb [-d|-h] <CONFIG FILE> [SEED] [NEVENTS] [OUTFILE]

    -t|--temp-directory [TMP DIR]
                : set the temporary working directory

    CONFIG FILE : see samples in the 'resources/' directory

    SEED        : seed for the random number generator (default is '${RANDOM}')

    NEVENTS     : number of events to be generated

    OUTFILE     : output file name

 Interactive mode:

  genbb

Example:

  genbb bipo212.conf 314159 100 /tmp/bipo212_out.genbb

EOF

}

while [ -n "$1" ]; do
    arg="$1"
    if [ "x${arg:0:1}" = "x-" ]; then

	if [ "${arg}" = "-d" -o "${arg}" = "--debug" ]; then
	    debug=1
	elif [ "${arg}" = "-h" -o "${arg}" = "--help" ]; then
	    usage
	    my_exit 2
	elif [ "${arg}" = "-t" -o "${arg}" = "--temp-directory" ]; then
	    shift 1
	    tmp_dir="$1"
	fi
    else
	if [ "x${config_file}" = "x" ]; then
	    config_file=${arg}
	elif [ "x${seed}" = "x" ]; then
	    seed=${arg}
	elif [ "x${nevents}" = "x" ]; then
	    nevents=${arg}
	elif [ "x${output_file}" = "x" ]; then
	    output_file=${arg}
	fi
    fi
    shift 1
done

if [ "x${config_file}" = "x" ]; then
    interactive=1
else
    if [ "x${seed}" = "x" ]; then
	seed=${RANDOM}
	echo "${appname}: NOTICE: Seed='${seed}' !" 1>&2
    fi
fi

which genbb1 1> /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "${appname}: ERROR: Missing 'genbb1' executable ! Abort !" 1>&2
    my_exit 1
fi
BIN=$(which genbb1)
echo "${appname}: NOTICE: Found '${BIN}' executable." 1>&2

if [ "x${tmp_dir}" = "x" ]; then
    tmp_dir=/tmp/${USER}
fi
if [ ! -d ${tmp_dir} ]; then
    mkdir -p ${tmp_dir}
fi
if [ ! -d ${tmp_dir} ]; then
    echo "${appname}: ERROR: Directory '${tmp_dir}' does not exist ! Abort !" 1>&2
    my_exit 1
fi

if [ ${interactive} -eq 0 ]; then
    echo "${appname}: NOTICE: Batch mode..." 1>&2
    tmp_conf=$(mktemp -p ${tmp_dir} genbb_XXXXXX )
    echo "${appname}: NOTICE: Set 'seed'..." 1>&2
    echo "seed=${seed}" > ${tmp_conf}.1
    echo "${appname}: NOTICE: seed=${seed}" 1>&2
    cat ${config_file} >> ${tmp_conf}.1
    echo "${appname}: NOTICE: nevents=${nevents}" 1>&2
    if [ "x${nevents}" != "x" ]; then
	echo "${appname}: NOTICE: Set 'number-of-events'..." 1>&2
	cat ${tmp_conf}.1 | sed -e "s@^number-of-events=.*@number-of-events=${nevents}@g" > ${tmp_conf}.2
	mv -f ${tmp_conf}.2 ${tmp_conf}.1
    fi

    if [ "x${output_file}" = "x" ]; then
	output_file="out.genbb"
    fi

    if [ "x${output_file}" != "x" ]; then
	out_ext=$(echo ${output_file} | tr '.' '\n' | tail -1)
	echo "${appname}: NOTICE: Output file has extension '${out_ext}'..." 1>&2
	if [ "x${out_ext}" != "xgenbb" ]; then
	    echo "${appname}: WARNING: Output file has not extension '.genbb'!" 1>&2
	fi
	echo "${appname}: NOTICE: Set 'output-file' to '${output_file}'..." 1>&2
	cat ${tmp_conf}.1 | sed \
	    -e "s@^output-file=.*@output-file=${output_file}@g" \
	    > ${tmp_conf}.2
	mv -f ${tmp_conf}.2 ${tmp_conf}.1
    fi
    mv -f ${tmp_conf}.1 ${tmp_conf} 
    cat ${tmp_conf}
    cat ${tmp_conf} | cut -d'=' -f2 | ${BIN}
else
    echo "${appname}: NOTICE: Interactive mode..." 1>&2
    echo "${appname}: NOTICE: BIN=${BIN}" 1>&2
    ${BIN}
fi

my_exit 0

# end of genbb
