# http://www-jlc.kek.jp/~miyamoto/Jupiter/html/_vis_viewer_.html
# A few possible commands:
#/vis/viewer/set/style surface
#/vis/viewer/set/style wireframe
#/vis/viewer/set/hiddenEdge 1
#/vis/scene/add/trajectories
#/vis/scene/add/hits
#/vis/viewer/reset
#/vis/viewer/panTo [right] [up] [unit]
#/vis/viewer/pan [right-increment] [up-increment] [unit]
#/vis/viewer/zoom 2
#/vis/viewer/zoomTo 2

#
#/vis/open OGLIX
/vis/open OGL
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 2
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
/vis/drawVolume

#