c genbb_help trick:
	print 29                                           
29	format('$number of events to generate      : ')    
	read *,nevents                                     
	print 30                                          
30	format('$number of first event [1]         : ')   
	read 31,ievstart                                  
31	format(i12)                                    
c end of genbb_help trick.
