#!/bin/bash
# -*- mode: shell-script; -*-
# genbb_help-config
#
# Note:
# This is a default config script provided by
# the mkskelpack program (from the PkgTools package).
# It suits the use of some default GNU/makefile
# generated in the package 'gmk' directory.
#
# Feel free to modify this file if you use another system
# to build/install this package (i.e. Autotools).
#
help=0

SCRIPTNAME="genbb_help-config"
THE_SYSTEM="$(uname -s)-$(uname -m | sed -e 's/ //g')"

THEPACK_ROOT=/usr/local
if [ -n "${GENBB_HELP_ROOT}" ]; then
    THEPACK_ROOT="${GENBB_HELP_ROOT}" 
else 
    echo "${SCRIPTNAME}: error: 'GENBB_HELP_ROOT' environment variable is not defined!" 
    exit 1
fi

PACK_CONF=${GENBB_HELP_ROOT}/.genbb_help.conf

THEPACK_INCLUDEDIR="${THEPACK_ROOT}/include" 

THEPACK_LIBDIR="${THEPACK_ROOT}/${THE_SYSTEM}/lib" 

THEPACK_BINDIR="${THEPACK_ROOT}/${THE_SYSTEM}/bin" 

THEPACK_VERSION=0.1.0
if [ -f "${THEPACK_ROOT}/VERSION" ]; then
    THEPACK_VERSION="$(cat ${THEPACK_ROOT}/VERSION)"    
elif [ -f "${THEPACK_ROOT}/pkgtools.d/package.info"  ]; then
    version=$(cat ${THEPACK_ROOT}/pkgtools.d/package.info | grep "version=" | cut -d'=' -f2 )    
    THEPACK_VERSION=$version
fi


cernlib_config=cernlib
if [ "x${CERNLIB_CONFIG}" != "x" ]; then
    cernlib_config=${CERNLIB_CONFIG}
fi

### Notes:
###	"-lgfortran " 
###	"-lg2c "
f77_comp=$(cat ${PACK_CONF} | grep F77_COMP= | cut -d= -f2)

#>>> 2009-03-01 FM:
# Remove  -lg2c link option for we now use gfortran...
#<<<
f77_opt=-lgfortran
if [ "x${f77_comp}" = "xg77" ]; then
    f77_opt=-lg2c
fi

opt=$1

if [ "x$opt" = "x" ]; then
    echo "${SCRIPTNAME}: error: Missing option!" 
    help=1
fi

if [ "x$opt" = "x--help" -o "x$opt" = "x-h" -o "x$opt" = "x-?" ]; then
    help=1
fi

if [ $help -eq 1 ]; then
    cat<<EOF
Usage: $SCRIPTNAME [OPTION]

Known values for OPTION are:

  --prefix              show genbb_help installation prefix
  --incdir              print include directory
  --libdir              print library directory
  --bindir              print binary directory
  --include             print include path pre-processor flags without dependencies 
  --cflags              print include path pre-processor flags with dependencies
  --libs                print library linking information, without dependencies
  --ldflags             
  --libs-depends        print library linking information, with dependencies
  --help                print this help then exit
  --version             print version information
  --system              print system

EOF
    exit 1
fi 

if [ "x$opt" = "x--system" ]; then
    echo "${THE_SYSTEM}"
    exit 0
fi 

if [ "x$opt" = "x--prefix" ]; then
    echo "${THEPACK_ROOT}"
    exit 0
fi 

if [ "x$opt" = "x--version" ]; then
    echo "${THEPACK_VERSION}"
    exit 0
fi 

if [ "x$opt" = "x--incdir" ]; then
    echo "${THEPACK_INCLUDEDIR}" 
    exit 0
fi

if [ "x$opt" = "x--include" ]; then
    echo "-I${THEPACK_INCLUDEDIR} " 
    exit 0
fi

if [ "x$opt" = "x--cflags" ]; then

    if [ "x${f77_comp}" = "xg77" ]; then
	f77_defines="\
-Df2cFortran \
-Dgenbbsub=genbbsub__ \
-Dset_random_seed=set_random_seed__ \
-Dgrndm=grndm__ \
-Dgenevent=genevent__ \
-Dgenbb_init_enrange=genbb_init_enrange__ \
-Denrange=enrange__\
"
	cernlib_cflags="-I${CERN_ROOT}/include"
    fi
    if [ "x${f77_comp}" = "xgfortran" ]; then
	f77_defines="\
-Df2cFortran \
-Dgenbbsub=genbbsub_ \
-Dset_random_seed=set_random_seed_ \
-Dgrndm=grndm_ \
-Dgenevent=genevent_ \
-Dgenbb_init_enrange=genbb_init_enrange_ \
-Denrange=enrange_ \
"
	cernlib_cflags="-I${CERN_ROOT}/include"
    fi
    ####
    shift 1
    more=$1
    if [ "x${more}" = "x--no-f77" ]; then
	f77_defines=
	cernlib_cflags=
    fi
    ###
    echo -n \
        "-fPIC " \
        "${f77_defines} " \
	"-I${THEPACK_INCLUDEDIR} "  \
	"`geomtools-config --cflags` "  \
	"`mygsl-config --cflags` "  \
	"`clhep-config --include` " \
	"${cernlib_cflags} " \
	| python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py
    exit 0
fi

if [ "x$opt" = "x--libdir" ]; then
    echo "${THEPACK_LIBDIR}"
    exit 0
fi 

if [ "x$opt" = "x--bindir" ]; then
    echo "${THEPACK_BINDIR}"
    exit 0
fi 

if [ "x$opt" = "x--libs" ]; then
    echo "-L${THEPACK_LIBDIR} -lgenbb_help "
    exit 0
fi 

if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
    cernlib_ldflags=`${cernlib_config} mathlib`
    ####
    shift 1
    more=$1
    if [ "x${more}" = "x--no-f77" ]; then
	cernlib_ldflags=
	f77_opt=
    fi
    ###
    echo -n "-L${THEPACK_LIBDIR} -lgenbb_help "  \
	"`geomtools-config --ldflags` "  \
	"`mygsl-config --ldflags` "  \
	"`clhep-config --libs` "  \
	"${cernlib_ldflags} "  \
	"${f77_opt} "  \
	"-lm "  \
	| python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py -r
    exit 0
fi 

echo "$SCRIPTNAME: error: Unknown option!" 
$0 --help
exit 1

# end of genbb_help-config
