//
// File generated by rootcint at Wed Nov  3 01:33:58 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include <brio/brio_dict.h>

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TArrayCMod_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_TArrayCMod(void *p = 0);
   static void *newArray_TArrayCMod(Long_t size, void *p);
   static void delete_TArrayCMod(void *p);
   static void deleteArray_TArrayCMod(void *p);
   static void destruct_TArrayCMod(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TArrayCMod*)
   {
      ::TArrayCMod *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TArrayCMod >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TArrayCMod", ::TArrayCMod::Class_Version(), "include/brio/TArrayCMod.h", 19,
                  typeid(::TArrayCMod), DefineBehavior(ptr, ptr),
                  &::TArrayCMod::Dictionary, isa_proxy, 0,
                  sizeof(::TArrayCMod) );
      instance.SetNew(&new_TArrayCMod);
      instance.SetNewArray(&newArray_TArrayCMod);
      instance.SetDelete(&delete_TArrayCMod);
      instance.SetDeleteArray(&deleteArray_TArrayCMod);
      instance.SetDestructor(&destruct_TArrayCMod);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TArrayCMod*)
   {
      return GenerateInitInstanceLocal((::TArrayCMod*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TArrayCMod*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void brio_record_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_brio_record(void *p = 0);
   static void *newArray_brio_record(Long_t size, void *p);
   static void delete_brio_record(void *p);
   static void deleteArray_brio_record(void *p);
   static void destruct_brio_record(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::brio_record*)
   {
      ::brio_record *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::brio_record >(0);
      static ::ROOT::TGenericClassInfo 
         instance("brio_record", ::brio_record::Class_Version(), "include/brio/brio_record.h", 33,
                  typeid(::brio_record), DefineBehavior(ptr, ptr),
                  &::brio_record::Dictionary, isa_proxy, 0,
                  sizeof(::brio_record) );
      instance.SetNew(&new_brio_record);
      instance.SetNewArray(&newArray_brio_record);
      instance.SetDelete(&delete_brio_record);
      instance.SetDeleteArray(&deleteArray_brio_record);
      instance.SetDestructor(&destruct_brio_record);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::brio_record*)
   {
      return GenerateInitInstanceLocal((::brio_record*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::brio_record*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TArrayCMod::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TArrayCMod::Class_Name()
{
   return "TArrayCMod";
}

//______________________________________________________________________________
const char *TArrayCMod::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TArrayCMod*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TArrayCMod::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TArrayCMod*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TArrayCMod::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TArrayCMod*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TArrayCMod::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TArrayCMod*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *brio_record::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *brio_record::Class_Name()
{
   return "brio_record";
}

//______________________________________________________________________________
const char *brio_record::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::brio_record*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int brio_record::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::brio_record*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void brio_record::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::brio_record*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *brio_record::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::brio_record*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TArrayCMod::__Streamer(TBuffer &R__b)
{
   // Stream an object of class TArrayCMod.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TArray::Streamer(R__b);
      //R__b.ReadArray(fArray);
      R__b.CheckByteCount(R__s, R__c, TArrayCMod::IsA());
   } else {
      R__c = R__b.WriteVersion(TArrayCMod::IsA(), kTRUE);
      TArray::Streamer(R__b);
      //R__b.WriteArray(fArray, __COUNTER__);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TArrayCMod::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TArrayCMod.
      TClass *R__cl = ::TArrayCMod::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fArray", &fArray);
      R__insp.Inspect(R__cl, R__parent, "fCapacity", &fCapacity);
      TArray::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TArrayCMod(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TArrayCMod : new ::TArrayCMod;
   }
   static void *newArray_TArrayCMod(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TArrayCMod[nElements] : new ::TArrayCMod[nElements];
   }
   // Wrapper around operator delete
   static void delete_TArrayCMod(void *p) {
      delete ((::TArrayCMod*)p);
   }
   static void deleteArray_TArrayCMod(void *p) {
      delete [] ((::TArrayCMod*)p);
   }
   static void destruct_TArrayCMod(void *p) {
      typedef ::TArrayCMod current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TArrayCMod

//______________________________________________________________________________
void brio_record::Streamer(TBuffer &R__b)
{
   // Stream an object of class brio_record.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      fSerialTag.Streamer(R__b);
      R__b >> fVersionTag;
      fDataBuffer.Streamer(R__b);
      R__b.CheckByteCount(R__s, R__c, brio_record::IsA());
   } else {
      R__c = R__b.WriteVersion(brio_record::IsA(), kTRUE);
      TObject::Streamer(R__b);
      fSerialTag.Streamer(R__b);
      R__b << fVersionTag;
      fDataBuffer.Streamer(R__b);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void brio_record::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class brio_record.
      TClass *R__cl = ::brio_record::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fSerialTag", &fSerialTag);
      fSerialTag.ShowMembers(R__insp, strcat(R__parent,"fSerialTag.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fVersionTag", &fVersionTag);
      R__insp.Inspect(R__cl, R__parent, "fDataBuffer", &fDataBuffer);
      fDataBuffer.ShowMembers(R__insp, strcat(R__parent,"fDataBuffer.")); R__parent[R__ncp] = 0;
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_brio_record(void *p) {
      return  p ? new(p) ::brio_record : new ::brio_record;
   }
   static void *newArray_brio_record(Long_t nElements, void *p) {
      return p ? new(p) ::brio_record[nElements] : new ::brio_record[nElements];
   }
   // Wrapper around operator delete
   static void delete_brio_record(void *p) {
      delete ((::brio_record*)p);
   }
   static void deleteArray_brio_record(void *p) {
      delete [] ((::brio_record*)p);
   }
   static void destruct_brio_record(void *p) {
      typedef ::brio_record current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::brio_record

/********************************************************
* brio_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablebrio_dict();

extern "C" void G__set_cpp_environmentbrio_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/brio/TArrayCMod.h");
  G__add_compiledheader("include/brio/brio_record.h");
  G__cpp_reset_tagtablebrio_dict();
}
#include <new>
extern "C" int G__cpp_dllrevbrio_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TArrayCMod */
static int G__brio_dict_147_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TArrayCMod* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TArrayCMod[n];
     } else {
       p = new((void*) gvp) TArrayCMod[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TArrayCMod;
     } else {
       p = new((void*) gvp) TArrayCMod;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArrayCMod*) G__getstructoffset())->Reserve((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArrayCMod*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArrayCMod*) G__getstructoffset())->__Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TArrayCMod::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TArrayCMod::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TArrayCMod::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TArrayCMod::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TArrayCMod*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TArrayCMod::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TArrayCMod::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TArrayCMod::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_147_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TArrayCMod::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__brio_dict_147_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TArrayCMod* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TArrayCMod(*(TArrayCMod*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TArrayCMod G__TTArrayCMod;
static int G__brio_dict_147_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TArrayCMod*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TArrayCMod*) (soff+(sizeof(TArrayCMod)*i)))->~G__TTArrayCMod();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TArrayCMod*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TArrayCMod*) (soff))->~G__TTArrayCMod();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__brio_dict_147_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TArrayCMod* dest = (TArrayCMod*) G__getstructoffset();
   *dest = *(TArrayCMod*) libp->para[0].ref;
   const TArrayCMod& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* brio_record */
static int G__brio_dict_159_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((brio_record*) G__getstructoffset())->reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   brio_record* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new brio_record[n];
     } else {
       p = new((void*) gvp) brio_record[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new brio_record;
     } else {
       p = new((void*) gvp) brio_record;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__brio_dictLN_brio_record));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) brio_record::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) brio_record::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) brio_record::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      brio_record::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((brio_record*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) brio_record::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) brio_record::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) brio_record::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__brio_dict_159_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) brio_record::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__brio_dict_159_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   brio_record* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new brio_record(*(brio_record*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__brio_dictLN_brio_record));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef brio_record G__Tbrio_record;
static int G__brio_dict_159_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (brio_record*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((brio_record*) (soff+(sizeof(brio_record)*i)))->~G__Tbrio_record();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (brio_record*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((brio_record*) (soff))->~G__Tbrio_record();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__brio_dict_159_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   brio_record* dest = (brio_record*) G__getstructoffset();
   *dest = *(brio_record*) libp->para[0].ref;
   const brio_record& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TArrayCMod */

/* brio_record */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncbrio_dict {
 public:
  G__Sizep2memfuncbrio_dict(): p(&G__Sizep2memfuncbrio_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncbrio_dict::*p)();
};

size_t G__get_sizep2memfuncbrio_dict()
{
  G__Sizep2memfuncbrio_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancebrio_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod))) {
     TArrayCMod *G__Lderived;
     G__Lderived=(TArrayCMod*)0x1000;
     {
       TArray *G__Lpbase=(TArray*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod),G__get_linked_tagnum(&G__brio_dictLN_TArray),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__brio_dictLN_brio_record))) {
     brio_record *G__Lderived;
     G__Lderived=(brio_record*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__brio_dictLN_brio_record),G__get_linked_tagnum(&G__brio_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablebrio_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__brio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__brio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TArrayCMod */
static void G__setup_memvarTArrayCMod(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod));
   { TArrayCMod *p; p=(TArrayCMod*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fArray)-(long)(p)),67,0,0,-1,G__defined_typename("Char_t"),-1,1,"fArray=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fCapacity)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCapacity=",0,"! Do not store the capacity");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__brio_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* brio_record */
static void G__setup_memvarbrio_record(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__brio_dictLN_brio_record));
   { brio_record *p; p=(brio_record*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fSerialTag)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__brio_dictLN_TString),-1,-1,1,"fSerialTag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fVersionTag)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"fVersionTag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fDataBuffer)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod),-1,-1,1,"fDataBuffer=",0,"Char_t *fArray and fN (from TArray)");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__brio_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarbrio_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTArrayCMod(void) {
   /* TArrayCMod */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod));
   G__memfunc_setup("TArrayCMod",950,G__brio_dict_147_0_1, 105, G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reserve",732,G__brio_dict_147_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__brio_dict_147_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Set",300,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - n", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetAt",469,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 8, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetAt",481,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - x i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("__Streamer",1025,G__brio_dict_147_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__brio_dict_147_0_8, 85, G__get_linked_tagnum(&G__brio_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TArrayCMod::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__brio_dict_147_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TArrayCMod::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__brio_dict_147_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TArrayCMod::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__brio_dict_147_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TArrayCMod::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__brio_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__brio_dict_147_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__brio_dict_147_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TArrayCMod::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__brio_dict_147_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TArrayCMod::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__brio_dict_147_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TArrayCMod::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__brio_dict_147_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TArrayCMod::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TArrayCMod", 950, G__brio_dict_147_0_20, (int) ('i'), G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod), -1, 0, 1, 1, 1, 0, "u 'TArrayCMod' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TArrayCMod", 1076, G__brio_dict_147_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__brio_dict_147_0_22, (int) ('u'), G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod), -1, 1, 1, 1, 1, 0, "u 'TArrayCMod' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncbrio_record(void) {
   /* brio_record */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__brio_dictLN_brio_record));
   G__memfunc_setup("reset",547,G__brio_dict_159_0_1, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("brio_record",1162,G__brio_dict_159_0_2, 105, G__get_linked_tagnum(&G__brio_dictLN_brio_record), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__brio_dict_159_0_3, 85, G__get_linked_tagnum(&G__brio_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&brio_record::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__brio_dict_159_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&brio_record::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__brio_dict_159_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&brio_record::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__brio_dict_159_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&brio_record::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__brio_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__brio_dict_159_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__brio_dict_159_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&brio_record::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__brio_dict_159_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&brio_record::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__brio_dict_159_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&brio_record::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__brio_dict_159_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&brio_record::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("brio_record", 1162, G__brio_dict_159_0_15, (int) ('i'), G__get_linked_tagnum(&G__brio_dictLN_brio_record), -1, 0, 1, 1, 1, 0, "u 'brio_record' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~brio_record", 1288, G__brio_dict_159_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__brio_dict_159_0_17, (int) ('u'), G__get_linked_tagnum(&G__brio_dictLN_brio_record), -1, 1, 1, 1, 1, 0, "u 'brio_record' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncbrio_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalbrio_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcbrio_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__brio_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_TArray = { "TArray" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_TArrayCMod = { "TArrayCMod" , 99 , -1 };
G__linked_taginfo G__brio_dictLN_brio_record = { "brio_record" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablebrio_dict() {
  G__brio_dictLN_TClass.tagnum = -1 ;
  G__brio_dictLN_TBuffer.tagnum = -1 ;
  G__brio_dictLN_TMemberInspector.tagnum = -1 ;
  G__brio_dictLN_TObject.tagnum = -1 ;
  G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__brio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__brio_dictLN_TString.tagnum = -1 ;
  G__brio_dictLN_TArray.tagnum = -1 ;
  G__brio_dictLN_TArrayCMod.tagnum = -1 ;
  G__brio_dictLN_brio_record.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablebrio_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__brio_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_TString);
   G__get_linked_tagnum_fwd(&G__brio_dictLN_TArray);
   G__tagtable_setup(G__get_linked_tagnum(&G__brio_dictLN_TArrayCMod),sizeof(TArrayCMod),-1,34048,"Array of chars",G__setup_memvarTArrayCMod,G__setup_memfuncTArrayCMod);
   G__tagtable_setup(G__get_linked_tagnum(&G__brio_dictLN_brio_record),sizeof(brio_record),-1,29952,"Basic BRIO record",G__setup_memvarbrio_record,G__setup_memfuncbrio_record);
}
extern "C" void G__cpp_setupbrio_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupbrio_dict()");
  G__set_cpp_environmentbrio_dict();
  G__cpp_setup_tagtablebrio_dict();

  G__cpp_setup_inheritancebrio_dict();

  G__cpp_setup_typetablebrio_dict();

  G__cpp_setup_memvarbrio_dict();

  G__cpp_setup_memfuncbrio_dict();
  G__cpp_setup_globalbrio_dict();
  G__cpp_setup_funcbrio_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncbrio_dict();
  return;
}
class G__cpp_setup_initbrio_dict {
  public:
    G__cpp_setup_initbrio_dict() { G__add_setup_func("brio_dict",(G__incsetup)(&G__cpp_setupbrio_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initbrio_dict() { G__remove_setup_func("brio_dict"); }
};
G__cpp_setup_initbrio_dict G__cpp_setup_initializerbrio_dict;

