#!/usr/bin/env bash

which recode > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "The 'decode' executable can not be found on this system ! Abort !" 1>&2
   exit 1
fi

which enscript > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "The 'enscript' executable can not be found on this system ! Abort !" 1>&2
   exit 1
fi

cat ${1} \
        | recode --diacritics u8..latin1 \
        | enscript --encoding=latin1 --line-numbers=1 \
        --highlight=cpp --color --language=html \
        --output=- \
        | recode --diacritics latin1..html | \
          sed -e 's@<pre>@<PRE>@g' -e 's@</pre>@</PRE>@g'  -e 's@<PRE>@\n<PRE>@g' -e 's@</PRE>@\n</PRE>@g'  | \
	  awk -f ./extract_pre.awk

#-e 's@</PRE>@</PRE>\n@g' | \
#

exit 0

# end