cccc
	print 29                                           ! comment
29	format('$number of events to generate      : ')    ! if in
	read *,nevents                                     ! nemo*.car
	print 30                                           !
30	format('$number of first event [1]         : ')    !
	read 31,ievstart                                   !
31	format(i12)                                        !**********
cccc
