#!/usr/bin/env bash
# -*- mode: shell-script; -*-
# mygsl-config
#
# Note:
# This is a default config script provided by
# the mkskelpack program (from the PkgTools package).
# It suits the use of some default GNU/makefile
# generated in the package 'gmk' directory.
#
# Feel free to modify this file if you use another system
# to build/install this package (i.e. Autotools).
#
#
# The following environment variables may be set to change 
# the behaviour of the mygsl-config script:
#
# export MYGSL_LDFLAGS_MODE="hardcoded_shared_lib_path"
#  will force the usage of hardcoded path name while linking against
#  a shared library (no use of -LPATH -lLIBNAME option)
#
# export MYGSL_USING_CACHE_FILES=0
#  will not use the cflags/ldflags cache accelerator files
#

opwd=$(pwd)
help=0

SCRIPTNAME="mygsl-config"
COMP=gcc
COMPVER=$(${COMP} --version | head -1 | cut -d ' ' -f 3)
COMPILER=-${COMP}${COMPVER}
COMPILER=

THE_SYSTEM="$(uname -s)-$(uname -m | sed -e 's/ //g')${COMPILER}"

THEPACK_ROOT=/usr/local
if [ -n "${MYGSL_ROOT}" ]; then
    THEPACK_ROOT="${MYGSL_ROOT}" 
else 
    echo "${SCRIPTNAME}: error: 'MYGSL_ROOT' environment variable is not defined!" 
    exit 1
fi

THEPACK_INCLUDEDIR="${THEPACK_ROOT}/include" 

THEPACK_LIBDIR="${THEPACK_ROOT}/${THE_SYSTEM}/lib" 

THEPACK_BINDIR="${THEPACK_ROOT}/${THE_SYSTEM}/bin" 

THEPACK_VERSION="?"
if [ -f "${THEPACK_ROOT}/VERSION" ]; then
    THEPACK_VERSION="$(cat ${THEPACK_ROOT}/VERSION)"    
elif [ -f "${THEPACK_ROOT}/pkgtools.d/package.info"  ]; then
    version=$(cat ${THEPACK_ROOT}/pkgtools.d/package.info | grep "version=" | cut -d'=' -f2 )    
    THEPACK_VERSION=${version}
fi

using_cache_files=0 # default: do not use cache files 
if [ "x${MYGSL_USING_CACHE_FILES}" != "x" ]; then
    if [ "x${MYGSL_USING_CACHE_FILES}" = "x0" ]; then
	using_cache_files=0
    else
	using_cache_files=1
    fi
fi
cflags_cache=${THEPACK_ROOT}/.cflags.cache
ldflags_cache=${THEPACK_ROOT}/.ldflags.cache

ldflags_mode=""
if [ "X${MYGSL_LDFLAGS_MODE}" != "X" ]; then
    ldflags_mode="${MYGSL_LDFLAGS_MODE}"
fi

opt=$1

if [ "x$opt" = "x" ]; then
    echo "${SCRIPTNAME}: error: Missing option!" 
    help=1
fi

if [ "x$opt" = "x--help" -o "x$opt" = "x-h" -o "x$opt" = "x-?" ]; then
    help=1
fi

if [ $help -eq 1 ]; then
    cat<<EOF
Usage: $SCRIPTNAME [OPTION]

Known values for OPTION are:

  --prefix              show mygsl installation prefix
  --incdir              print include directory
  --libdir              print library directory
  --bindir              print binary directory
  --include             print include path pre-processor flags without dependencies 
  --cflags              print include path pre-processor flags with dependencies
  --libs                print library linking information, without dependencies
  --ldflags             
  --libs-depends        print library linking information, with dependencies
  --help                print this help then exit
  --gsl-ldpath          print the path to GSL libraries             
  --gsl-incpath         print the path to GSL headers             
  --gsl-version         print the GSL version             
  --version             print version information
  --system              print system
  --check               check dependencies and setup
  --clean-cache-files   clean compile/link cache files

EOF
    exit 1
fi 

gsl_config_def=$(which gsl-config)
gsl_version_def=$(${gsl_config_def} --version)
gsl_prefix_def=$(${gsl_config_def} --prefix)

if [ "x${GSL_BASE_DIR}" != "x" ]; then
    if [ ! -d "${GSL_BASE_DIR}" ]; then
	echo "$SCRIPTNAME: error: GSL_BASE_DIR='${GSL_BASE_DIR}' is not a valid directory! Abort!" 1>&2
	exit 1
    fi
    gsl_config=$(find ${GSL_BASE_DIR}/bin -mindepth 1 -maxdepth 1 -name "gsl-config")
    gsl_version=$(${gsl_config} --version)
    gsl_prefix=$(${gsl_config} --prefix)
else
    gsl_config=${gsl_config_def}
    gsl_version=${gsl_version_def}
    gsl_prefix=${gsl_prefix_def}
fi

gsl_major=$(echo ${gsl_version} | cut -d'.' -f1)
gsl_minor=$(echo ${gsl_version} | cut -d'.' -f2)
if [ ${gsl_major} -lt 1 ]; then
    echo "$SCRIPTNAME: error: GSL version ${gsl_version} is not suitable! Abort!" 1>&2
    exit 1
elif [ ${gsl_major} -eq 1 -a ${gsl_minor} -lt 10 ]; then
    echo "$SCRIPTNAME: error: GSL version ${gsl_version} is not suitable! Abort!" 1>&2
    exit 1
fi

if [ "x$opt" = "x--test" ]; then
    if [ "x${GSL_BASE_DIR}" != "x" ]; then
	echo "$SCRIPTNAME: warning: a special GSL installation is forced using the GSL_BASE_DIR='${GSL_BASE_DIR}'!" 1>&2
    fi
    cat <<EOF
mygsl-config tests:
  Default system GSL prefix is:  ${gsl_prefix_def}
  Default system GSL version is: ${gsl_version_def}
  Default system GSL config is:  ${gsl_config_def}
EOF
    echo -n "  Current GSL base directory is: ${gsl_prefix}" 
    if [ "x${GSL_BASE_DIR}" != "x" ]; then
	cat <<EOF
 (from the GSL_BASE_DIR environment variable)
EOF
    else
	cat <<EOF
 (corresponds to the system\'s default version)
EOF
    fi
    
    cat <<EOF
  Current GSL version is:        ${gsl_version}
  Current GSL config is:         ${gsl_config}
  Current PATH is:               ${PATH}
  Current LD_LIBRARY_PATH is:    ${LD_LIBRARY_PATH}
EOF
    exit 0
fi 

if [ "x$opt" = "x--system" ]; then
    echo "${THE_SYSTEM}"
    exit 0
fi 

if [ "x$opt" = "x--prefix" ]; then
    echo "${THEPACK_ROOT}"
    exit 0
fi 

if [ "x$opt" = "x--version" ]; then
    echo "${THEPACK_VERSION}"
    exit 0
fi 

if [ "x$opt" = "x--clean-cache-files" ]; then
    if [ -f ${cflags_cache} ]; then
	echo "${SCRIPTNAME}: NOTICE: Removing '${cflags_cache}' cache file !" >&2
	rm -f ${cflags_cache}
    fi
    if [ -f ${ldflags_cache} ]; then
	echo "${SCRIPTNAME}: NOTICE: Removing '${ldflags_cache}' cache file !" >&2
	rm -f ${ldflags_cache}
    fi
    exit 0
fi

if [ "x$opt" = "x--incdir" ]; then
    echo "${THEPACK_INCLUDEDIR}" 
    exit 0
fi

if [ "x$opt" = "x--include" ]; then
    echo "-I${THEPACK_INCLUDEDIR} " 
    exit 0
fi

if [ "x$opt" = "x--cflags" ]; then
    generate_cflags=0
    if [ ${using_cache_files} -eq 1 ]; then
	if [ -f ${cflags_cache} ]; then
	    cat ${cflags_cache}
	    exit 0
	else
	    generate_cflags=1
	fi
    else
	generate_cflags=1
    fi
	    
    if [ ${generate_cflags} -eq 1 ]; then
	(
	    echo -n \
		"-fPIC " \
		"-I${THEPACK_INCLUDEDIR} "  \
         "`gsl-config --cflags` "  \
	    | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py	    
	) | tee ${cflags_cache}
	test ${using_cache_files} -eq 0 && rm -f ${cflags_cache}
    fi
    exit 0
fi

if [ "x$opt" = "x--libdir" ]; then
    echo "${THEPACK_LIBDIR}"
    exit 0
fi 

if [ "x$opt" = "x--bindir" ]; then
    echo "${THEPACK_BINDIR}"
    exit 0
fi 

if [ "x$opt" = "x--gsl-incpath" ]; then
    gsl_inc_path=$(gsl-config --cflags | tr -s ' ' | tr ' ' '\n' | grep "\-I")
    echo "${gsl_inc_path}"
    exit 0
fi

if [ "x$opt" = "x--gsl-ldpath" ]; then
    gsl_ld_path=$(gsl-config --libs | tr -s ' ' | tr ' ' '\n' | grep "\-L")
    echo "${gsl_ld_path}"
    exit 0
fi

if [ "x$opt" = "x--gsl-version" ]; then
    echo "${gsl_version}"
    exit 0
fi

if [ "x$opt" = "x--libs" ]; then
    echo "-L${THEPACK_LIBDIR} -lmygsl "
    exit 0
fi 

if [ "x$opt" = "x--libs-depends" -o "x$opt" = "x--ldflags" ]; then
    generate_ldflags=0
    if [ ${using_cache_files} -eq 1 ]; then
	if [ -f ${ldflags_cache} ]; then
	    cat ${ldflags_cache}
	    exit 0
	else
	    generate_ldflags=1
	fi
    else
	generate_ldflags=1
    fi
    
    if [ ${generate_ldflags} -eq 1 ]; then	
	(
	    (
		if [ "X${ldflags_mode}" = "Xhardcoded_shared_lib_path" ]; then
		    echo -n "${THEPACK_LIBDIR}/libmygsl.so "
		else
		    echo -n "-L${THEPACK_LIBDIR} -lmygsl "
		fi
		echo -n ""  \
         "`gsl-config --libs` "  \
	    ) | python ${THEPACK_ROOT}/pkgtools.d/mkuniqueflags.py -r
	) | tee ${ldflags_cache}
	test ${using_cache_files} -eq 0 && rm -f ${ldflags_cache}
    fi
    exit 0
fi 

if [ "x$opt" = "x--check" ]; then
    cd ${THEPACK_ROOT}
    ${THEPACK_ROOT}/pkgtools.d/pkgtool check
    if [ $? -ne 0 ]; then
	echo "$SCRIPTNAME: error: Check procedure failed!" >&2
	cd ${opwd}
	exit 1
    fi
    cd ${opwd}
    exit 0
fi 

echo "$SCRIPTNAME: error: Unknown option '${opt}'!"  >&2
$0 --help
exit 1

# end of mygsl-config
