# - Functions and macros for manipulating paths and files
#
# This module provides some convenience functions and macros to manipulate
# file and directory paths based on the builtin CMake tools.
#
# function GET_CURRENT_LIST_DIR(outvar)
#     Set outvar to the absolute path of the directory containing the CMake
#     list file in which the function was called. Note that in CMake => 2.8.3
#     one can use the standard variable CMAKE_CURRENT_LIST_DIR instead.
#
# function GET_ABSOLUTE_PATHS(outvar inpaths)
#     Convert each path in inpaths to be an absolute path and set outvar
#     to the list of these absolute paths.
#
#----------------------------------------------------------------------------
# Copyright 2011 Ben Morgan <Ben.Morgan@warwick.ac.uk>
# Copyright 2011 University of Warwick
#----------------------------------------------------------------------------
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
# function GET_CURRENT_LIST_DIR
#
function(GET_CURRENT_LIST_DIR _var)
    get_filename_component(__tmpvar ${CMAKE_CURRENT_LIST_FILE} PATH)
    set(${_var} ${__tmpvar} PARENT_SCOPE)
endfunction()


#----------------------------------------------------------------------------
# function GET_ABSOLUTE_PATHS
#
function(GET_ABSOLUTE_PATHS _var _paths)
    foreach(__p in ${_paths})
        get_filename_component(__tmp_abs_path ${__p} ABSOLUTE)
        list(APPEND __abs_paths ${__tmp_abs_path})
    endforeach()

    set(${_var} ${__abs_paths} PARENT_SCOPE)
endfunction()


