/********************************************************************
* brio_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error brio_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablebrio_dict();
extern void G__cpp_setup_inheritancebrio_dict();
extern void G__cpp_setup_typetablebrio_dict();
extern void G__cpp_setup_memvarbrio_dict();
extern void G__cpp_setup_globalbrio_dict();
extern void G__cpp_setup_memfuncbrio_dict();
extern void G__cpp_setup_funcbrio_dict();
extern void G__set_cpp_environmentbrio_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <brio/detail/TArrayCMod.h>
#include <brio/detail/brio_record.h>
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__brio_dictLN_TClass;
extern G__linked_taginfo G__brio_dictLN_TBuffer;
extern G__linked_taginfo G__brio_dictLN_TMemberInspector;
extern G__linked_taginfo G__brio_dictLN_TObject;
extern G__linked_taginfo G__brio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__brio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__brio_dictLN_TString;
extern G__linked_taginfo G__brio_dictLN_TArray;
extern G__linked_taginfo G__brio_dictLN_TArrayCMod;
extern G__linked_taginfo G__brio_dictLN_brio_record;

/* STUB derived class for protected member access */
